# **Using *MiniLMv2-L12-MNLI/XNLI* for New Fields Creation**

# All Imports Here

In [70]:
import os
glb_pth = 'd:\\GitHub\\SaaS_Product_Analysis'
os.chdir(glb_pth)

import re
import pandas as pd
import json
import torch
from pathlib import Path
from transformers import pipeline

# Importing Datasets

In [71]:
data_pth = 'data\\cleaned'

zoom_df = pd.read_csv(f'{glb_pth}\\{data_pth}\\zoom_reviews_clean.csv')
meet_df = pd.read_csv(f'{glb_pth}\\{data_pth}\\meet_reviews_clean.csv')
teams_df = pd.read_csv(f'{glb_pth}\\{data_pth}\\teams_reviews_clean.csv')
webex_df = pd.read_csv(f'{glb_pth}\\{data_pth}\\webex_reviews_clean.csv')

# Implementing Model

## *Testing MiniLMv2-L12-MNLI/XNLI*

In [72]:
pipe = pipeline(
    'zero-shot-classification',
    model='MoritzLaurer/multilingual-MiniLMv2-L12-mnli-xnli'
)

Loading weights: 100%|██████████| 201/201 [00:00<00:00, 5886.19it/s]

In [73]:
sequence_to_classify = (
    "🤬🤬🤬"
)

candidate_labels = ['positive', 'negative', 'neutral']

output = pipe(sequence_to_classify, candidate_labels)

max_prob = max(output['scores'])
max_idx = output['scores'].index(max_prob)

print(f'Prediction: {output['labels'][max_idx].capitalize()}\nProb: {round(max_prob, 2)*100.0}%')
print(output)

Prediction: Positive
Prob: 62.0%
{'sequence': '🤬🤬🤬', 'labels': ['positive', 'negative', 'neutral'], 'scores': [0.6238628029823303, 0.23767931759357452, 0.13845789432525635]}

## *Using on datasets*

In [74]:
def sentiment_prediction(body):
    candidate_labels = ['positive', 'negative', 'neutral']
    probs = []
    labels = []
    for i, texts in enumerate(body):
        output = pipe(texts, candidate_labels)
        max_prob = max(output['scores'])
        max_label = output['labels'][
            output['scores'].index(max_prob)
        ]
        probs.append(max_prob)
        labels.append(max_label)
        if i % 100 == 0:
            print(f'Processed {i} reviews')
    return (probs, labels)

In [75]:
zoom_df['sentiment_score'], zoom_df['sentiment_label'] = (
    sentiment_prediction(zoom_df['body'])
)

Processed 0 reviews
Processed 100 reviews
Processed 200 reviews
Processed 300 reviews
Processed 400 reviews
Processed 500 reviews
Processed 600 reviews
Processed 700 reviews
Processed 800 reviews
Processed 900 reviews
Processed 1000 reviews
Processed 1100 reviews
Processed 1200 reviews
Processed 1300 reviews
Processed 1400 reviews
Processed 1500 reviews
Processed 1600 reviews
Processed 1700 reviews
Processed 1800 reviews
Processed 1900 reviews
Processed 2000 reviews
Processed 2100 reviews
Processed 2200 reviews
Processed 2300 reviews
Processed 2400 reviews
Processed 2500 reviews
Processed 2600 reviews
Processed 2700 reviews
Processed 2800 reviews
Processed 2900 reviews
Processed 3000 reviews
Processed 3100 reviews
Processed 3200 reviews
Processed 3300 reviews
Processed 3400 reviews
Processed 3500 reviews
Processed 3600 reviews
Processed 3700 reviews
Processed 3800 reviews
Processed 3900 reviews
Processed 4000 reviews
Processed 4100 reviews
Processed 4200 reviews
Processed 4300 reviews
Processed 4400 reviews
Processed 4500 reviews
Processed 4600 reviews
Processed 4700 reviews
Processed 4800 reviews
Processed 4900 reviews
Processed 5000 reviews
Processed 5100 reviews
Processed 5200 reviews
Processed 5300 reviews
Processed 5400 reviews
Processed 5500 reviews
Processed 5600 reviews
Processed 5700 reviews
Processed 5800 reviews
Processed 5900 reviews

In [82]:
zoom_df.head(20)

,Unnamed: 0,reviewId,rating,body,appVersion,timestamp,sentiment_score,sentiment_label
0,0,0dcdf6d4-dfa0-4401-b3d4-d9dbc27c825f,1,👎👎👎👎👎,NaN,2026-08-26 05:50:54,0.525908,positive
1,1,d70e1f1c-83fc-495b-8035-3eb460431f82,1,Can't login after resignation,NaN,2026-08-26 05:50:12,0.367690,neutral
2,2,ad750e18-d0d4-40cc-8797-26e77acdbfe4,1,Worst app,NaN,2026-08-26 05:49:41,0.838597,negative
3,3,359d855e-2a8b-4313-8120-91dff1c872ef,1,Can't login,NaN,2026-08-26 05:49:09,0.515222,neutral
4,4,dae23cb0-c77e-4f78-89ea-72b01e4c7799,1,Can't login after resignation,NaN,2026-08-26 05:48:36,0.367690,neutral
5,5,a6aea44a-1e7a-40a0-900c-f29ea807b1aa,1,Can't login after resignation,NaN,2026-08-26 05:48:10,0.367690,neutral
6,6,c819e071-cbc7-4bf2-88c6-3cb5af6e970a,1,Tôi đã nhập đúng passcode nhưng ứng dụng lại t...,7.1.6.41876,2026-08-26 05:46:55,0.747485,negative
7,7,ef8e0a4d-9ec1-4edc-9868-5040eed5be7d,5,very good,NaN,2026-08-26 05:15:05,0.981104,positive
8,8,29d469f8-6259-4055-859b-270e6ac0aaf6,1,why i cant get in any zoom meetings? please fi...,7.1.6.41876,2026-08-26 04:56:37,0.423605,negative
9,9,d8d05f54-6fae-4a90-8d58-9d2d53163965,5,👍👍👌👌🇮🇳🇮🇳🎉🎉👌👌,7.1.6.41876,2026-08-26 04:32:55,0.700381,positive
10,10,14bf8bf2-a105-45f5-87f2-d6db87cc85f5,1,I cannot get the fake background to turn off! ...,7.1.6.41876,2026-08-26 02:14:28,0.368070,positive
11,11,f3e6ed92-c9d5-4ef4-84f4-c4fbed03317b,1,forces actions on users. will delete immediate...,7.1.6.41876,2026-08-26 00:02:07,0.384982,positive
12,12,02c81155-f54c-4552-b93a-d825f66223d6,5,Good,7.1.6.41876,2026-08-25 22:39:17,0.971225,positive
13,13,d56916d5-852e-497f-b046-fa5a8b01a309,5,loud and clear,7.1.6.41876,2026-08-25 22:20:33,0.804145,positive
14,14,5e037c20-dfd9-498e-a22b-82dff4fba792,5,I have had some trouble getting in through the...,7.1.6.41876,2026-08-25 19:30:05,0.723111,positive
15,15,aa42f6fb-72a5-48c2-931f-c5021db3b4e2,5,so nice,7.1.0.41065,2026-08-25 18:33:19,0.976873,positive
16,16,03e3fc3e-fa8b-4a19-bb09-78614460924d,5,Thank you,7.1.6.41876,2026-08-25 16:58:53,0.940167,positive
17,17,9d7f788a-35d7-4556-a4f2-5c80d3aa217f,5,good app,7.1.6.41876,2026-08-25 16:46:31,0.981120,positive
18,18,a7f1645b-7c65-4058-8edb-e96666d6ba17,5,First time is the charm! It is easy to use & s...,NaN,2026-08-25 15:57:19,0.898007,positive
19,19,88fe0a9f-a523-4daf-8a99-86041cda9b14,5,zindagi,7.1.6.41876,2026-08-25 15:57:07,0.823169,positive

In [77]:
teams_df['sentiment_score'], teams_df['sentiment_label'] = (
    sentiment_prediction(teams_df['body'])
)

Processed 0 reviews
Processed 100 reviews
Processed 200 reviews
Processed 300 reviews
Processed 400 reviews
Processed 500 reviews
Processed 600 reviews
Processed 700 reviews
Processed 800 reviews
Processed 900 reviews
Processed 1000 reviews
Processed 1100 reviews
Processed 1200 reviews
Processed 1300 reviews
Processed 1400 reviews
Processed 1500 reviews
Processed 1600 reviews
Processed 1700 reviews
Processed 1800 reviews
Processed 1900 reviews
Processed 2000 reviews
Processed 2100 reviews
Processed 2200 reviews
Processed 2300 reviews
Processed 2400 reviews
Processed 2500 reviews
Processed 2600 reviews
Processed 2700 reviews
Processed 2800 reviews
Processed 2900 reviews
Processed 3000 reviews
Processed 3100 reviews
Processed 3200 reviews
Processed 3300 reviews
Processed 3400 reviews
Processed 3500 reviews
Processed 3600 reviews
Processed 3700 reviews
Processed 3800 reviews
Processed 3900 reviews
Processed 4000 reviews
Processed 4100 reviews
Processed 4200 reviews
Processed 4300 reviews
Processed 4400 reviews
Processed 4500 reviews
Processed 4600 reviews
Processed 4700 reviews
Processed 4800 reviews
Processed 4900 reviews
Processed 5000 reviews
Processed 5100 reviews
Processed 5200 reviews
Processed 5300 reviews
Processed 5400 reviews
Processed 5500 reviews
Processed 5600 reviews
Processed 5700 reviews
Processed 5800 reviews
Processed 5900 reviews

In [78]:
teams_df.head()

,Unnamed: 0,reviewId,rating,body,appVersion,timestamp,sentiment_score,sentiment_label
0,0,c7424e1f-784c-4bea-a863-93cbf4d6a0d9,1,"It literally won't load, it's just useless on ...",1416/1.0.0.2026142702,2026-08-26 07:07:02,0.492487,neutral
1,1,b0c158ef-e997-4489-a696-64874318d661,5,it's de best app for online meetings 🥰,1416/1.0.0.2026142702,2026-08-26 06:22:02,0.961203,positive
2,2,dce12548-3288-4fcb-94f2-47361c5de3d4,5,Great app,1416/1.0.0.2026142702,2026-08-26 06:13:26,0.986904,positive
3,3,6bd53442-17bc-4d3d-ae16-2f00feb338eb,1,i am facing glitch during calls suddenly sound...,1416/1.0.0.2026142702,2026-08-26 05:54:12,0.534968,negative
4,4,f0f2fd5d-b67a-486e-8b5e-7de5fd218e14,1,totally waste my college account never login t...,1416/1.0.0.2026142702,2026-08-26 05:53:07,0.715226,negative

In [79]:
meet_df['sentiment_score'], meet_df['sentiment_label'] = (
    sentiment_prediction(meet_df['body'])
)

Processed 0 reviews
Processed 100 reviews
Processed 200 reviews
Processed 300 reviews
Processed 400 reviews
Processed 500 reviews
Processed 600 reviews
Processed 700 reviews
Processed 800 reviews
Processed 900 reviews
Processed 1000 reviews
Processed 1100 reviews
Processed 1200 reviews
Processed 1300 reviews
Processed 1400 reviews
Processed 1500 reviews
Processed 1600 reviews
Processed 1700 reviews
Processed 1800 reviews
Processed 1900 reviews
Processed 2000 reviews
Processed 2100 reviews
Processed 2200 reviews
Processed 2300 reviews
Processed 2400 reviews
Processed 2500 reviews
Processed 2600 reviews
Processed 2700 reviews
Processed 2800 reviews
Processed 2900 reviews
Processed 3000 reviews
Processed 3100 reviews
Processed 3200 reviews
Processed 3300 reviews
Processed 3400 reviews
Processed 3500 reviews
Processed 3600 reviews
Processed 3700 reviews
Processed 3800 reviews
Processed 3900 reviews
Processed 4000 reviews
Processed 4100 reviews
Processed 4200 reviews
Processed 4300 reviews
Processed 4400 reviews
Processed 4500 reviews
Processed 4600 reviews
Processed 4700 reviews
Processed 4800 reviews
Processed 4900 reviews
Processed 5000 reviews
Processed 5100 reviews
Processed 5200 reviews
Processed 5300 reviews
Processed 5400 reviews
Processed 5500 reviews
Processed 5600 reviews
Processed 5700 reviews
Processed 5800 reviews
Processed 5900 reviews

In [80]:
meet_df.head()

,Unnamed: 0,reviewId,rating,body,appVersion,timestamp,sentiment_score,sentiment_label
0,0,425f3803-d4e3-4cae-abb5-6b6aff5a0ffb,5,Malinaw at matagal maputol ang tawag.,371.0.958218800.duo.android_20260803.01_p0,2026-08-26 07:20:13,0.554303,neutral
1,1,79aab19f-bddd-4ceb-a88f-0812e1e882c4,5,nice,371.0.963601321.duo.android_20260803.01_p4,2026-08-26 07:15:24,0.963980,positive
2,2,81533c07-6961-40da-aaf4-57874055c464,5,Masud Aalam,372.0.968082697.duo.android_20260810.02_p4,2026-08-26 05:36:24,0.591646,positive
3,3,a889eea4-571f-4e34-a49d-babfcb3b7aee,5,It works and I think it works very well.,371.0.958218800.duo.android_20260803.01_p0,2026-08-26 05:06:07,0.987607,positive
4,4,38154815-a509-4214-a9bd-20e49d424b69,1,LISTEN TO THE DHAMMA TO KNOW THE TRUTH သစၥာသိဖ...,371.0.963601321.duo.android_20260803.01_p4,2026-08-26 04:34:37,0.800422,positive

In [81]:
webex_df['sentiment_score'], webex_df['sentiment_label'] = (
    sentiment_prediction(webex_df['body'])
)

Processed 0 reviews
Processed 100 reviews
Processed 200 reviews
Processed 300 reviews
Processed 400 reviews
Processed 500 reviews
Processed 600 reviews
Processed 700 reviews
Processed 800 reviews
Processed 900 reviews
Processed 1000 reviews
Processed 1100 reviews
Processed 1200 reviews
Processed 1300 reviews
Processed 1400 reviews
Processed 1500 reviews
Processed 1600 reviews
Processed 1700 reviews
Processed 1800 reviews
Processed 1900 reviews
Processed 2000 reviews
Processed 2100 reviews
Processed 2200 reviews
Processed 2300 reviews
Processed 2400 reviews
Processed 2500 reviews
Processed 2600 reviews
Processed 2700 reviews
Processed 2800 reviews
Processed 2900 reviews
Processed 3000 reviews
Processed 3100 reviews
Processed 3200 reviews
Processed 3300 reviews
Processed 3400 reviews
Processed 3500 reviews
Processed 3600 reviews
Processed 3700 reviews
Processed 3800 reviews
Processed 3900 reviews

TypeError: object of type 'float' has no len()

In [ ]:
webex_df.head()